version: "3"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: kursova_project_java
      MYSQL_ROOT_PASSWORD: root
