USE students_db;

# FACULTIES

INSERT INTO FACULTY
VALUES ('IKCT');
INSERT INTO FACULTY
VALUES ('IKT');
INSERT INTO FACULTY
VALUES ('FTAU');
INSERT INTO FACULTY
VALUES ('IT');
INSERT INTO FACULTY
VALUES ('IC');

# GROUPS

INSERT INTO `GROUP`
VALUES ('IA-302', 'IT', 124, 3);
INSERT INTO `GROUP`
VALUES ('IS-101', 'IKCT', 122, 1);
INSERT INTO `GROUP`
VALUES ('OP-202', 'FTAU', 064, 2);
INSERT INTO `GROUP`
VALUES ('IK-201', 'IKT', 125, 2);
INSERT INTO `GROUP`
VALUES ('MN-401', 'IC', 074, 4);

# STUDENTS

INSERT INTO STUDENT
VALUES (1, 'Oleg', 'Olegov', 'Olegovich', 'CONTRACT', 'IKCT', 'IS-101', 88.3);
INSERT INTO STUDENT
VALUES (2, 'Dima', 'Dimov', 'Dimovich', 'CONTRACT', 'FTAU', 'OP-202', 86.4);
INSERT INTO STUDENT
VALUES (3, 'Alena', 'Alenovna', 'Alenovich', 'BUDGET', 'IT', 'IA-302', 70.6);
INSERT INTO STUDENT
VALUES (4, 'Dasha', 'Dashev', 'Dashevich', 'BUDGET', 'IKT', 'IK-201', 93.9);
INSERT INTO STUDENT
VALUES (5, 'Abdul', 'Abdulov', 'Abdulovich', 'CONTRACT', 'IKT', 'IK-201', 73.5);
INSERT INTO STUDENT
VALUES (6, 'Vlad', 'Vladov', 'Vladovich', 'CONTRACT', 'IC', 'MN-401', 64.6);
